# Generated by Django 5.1.7 on 2025-03-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('organic', 'Organic'), ('inorganic', 'Inorganic')], max_length=10)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FineSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='myapp.fine')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('company', models.CharField(max_length=255)),
                ('fund', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('working', 'Working'), ('repair', 'Repair'), ('damaged', 'Damaged')], default='working', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='myapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('nos', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='myapp.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_no', models.CharField(max_length=50, unique=True)),
                ('roll_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('passout', 'Passout')], default='active', max_length=10)),
                ('batch', models.CharField(max_length=10)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.coursetype')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='fine',
            name='admission_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student', to_field='admission_no'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier', to_field='code'),
        ),
        migrations.CreateModel(
            name='ChemicalSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('company', models.CharField(max_length=255)),
                ('fund', models.CharField(max_length=255)),
                ('exp_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('nos', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('chem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='myapp.chemical')),
            ],
            options={
                'unique_together': {('chem_id', 'exp_date')},
            },
        ),
    ]
