# Generated by Django 5.1.7 on 2025-03-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_purchasesub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesub',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
    ]
