# Generated by Django 5.1.7 on 2025-03-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_purchasesub_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Discarded', 'Discarded')], default='Pending', max_length=10)),
                ('supplier_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='PendingPurchaseSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('nos', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='myapp.pendingpurchase')),
            ],
        ),
    ]
