# Generated by Django 5.1.7 on 2025-03-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pendingpurchase_pendingpurchasesub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpurchasesub',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
