# Generated by Django 5.1.7 on 2025-03-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_pendingpurchasesub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalsub',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalsub',
            name='fund',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalsub',
            name='nos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chemicalsub',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
