# Generated by Django 5.1.7 on 2025-03-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_chemicalsub_company_alter_chemicalsub_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalsub',
            name='company',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicalsub',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemicalsub',
            name='fund',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicalsub',
            name='nos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='chemicalsub',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
