# Generated by Django 5.1.7 on 2025-03-24 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_dailyusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to='myapp.chemicalsub'),
        ),
    ]
