# Generated by Django 5.1.7 on 2025-03-25 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_dailyusage_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsagePending',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('batch', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chemicalsub')),
            ],
        ),
    ]
